version: 2
updates:
  # Jetty 9
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-9.4.x"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "jetty-9.4.x"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
  # Jetty 10
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-10.0.x"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "jetty-10.0.x"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
  # Jetty 11
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-11.0.x"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "jetty-11.0.x"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"